# common arguments
device: cuda:2
seed: 3
model: &model padim
backbone: &backbone resnet18  # Support resnet18, resnet50, wide_resnet50_2
pretrained_model_path: null # checkpoints/resnet18.pth

# dataset arguments
batch_size: 1
num_workers: 0
category: &category tyre
resize: [256, 256]
crop_size: [256, 256]
data_path: /data/data_wbw/data/cropped_tyre/1-按规格显著病茨/7.00R16-8PR[CR908+A]朝阳无内 AA/train_2000/1 # /data/data_wbw/data/cropped_tyre/006163123012900_3/train/
save_path: [output/, *model, _, *backbone, _, *category]
save_name: &save_name 7.00R16-8PR_2000_1.pth

# train arguments
do_eval: False  # After training, whether to eval model;

# val and predict arguments
save_pic: True # Whether to save one output example picture in val and predict;
model_path: [output/, *model, _, *backbone, _, *category, /, *save_name]

# predict arguments
img_path: /data/data_wbw/data/cropped_tyre/1-按规格显著病茨/7.00R16-8PR[CR908+A]朝阳无内 AA/val_2000/1 # /data/data_wbw/data/cropped_tyre/006163125019100_3/test/A011160517_0.jpg
result_path: [output/, *model, _, *backbone, _, *category, '/7.00R16-8PR[CR908+A]朝阳无内 AA_val_2000_1'] 
threshold: 12