# common arguments
device: cuda:1
seed: 3
model: &model patchcore
backbone: &backbone resnet50  # Support resnet18, resnet50, wide_resnet50_2
method: coreset # projection method, one of [sample, ortho, svd_ortho, gaussian, coreset]
k: 10  # using feature channels
pretrained_model_path: checkpoints/resnet50.pth # checkpoints/resnet18.pth

# dataset arguments
max_size: 1000
batch_size: 1
num_workers: 0
category: &category tyre
resize: [256, 256]
crop_size: [256, 256]
data_path: /data/data_wbw/data/cropped_tyre/Tyre_AD/650R16-12PR-CR926-1614_side/train/good/ # /data/data_wbw/data/cropped_tyre/006163123012900_3/train/ # /data2/chen/spec10k/006163123012900
save_path: [output/, *model, _, *backbone, _, *category]
save_name: &save_name 700R16-8PR-EZ525-1614_side.pth

# train arguments
do_eval: False  # After training, whether to eval model;

# val and predict arguments
save_pic: True # Whether to save one output example picture in val and predict;
model_path: [output/, *model, _, *backbone, _, *category, /, *save_name]

# predict arguments
save_all: True
img_path: test_imgs/C3D1D21173_side # /data/data_wbw/data/cropped_tyre/006163123012900_3/test/A011141165_0.jpg
result_path: [output/, *model, _, *backbone, _, *category, '/700R16-8PR-EZ525-1614_side']
threshold: 1.8