# common arguments
device: cuda:1
seed: 3
model: &model stfpm
backbone: &backbone resnet18  # Support resnet18, resnet50, wide_resnet50_2

# dataset arguments
batch_size: 1
num_workers: 0
category: &category tyre  # Category name for MvTec AD dataset, also support one of [textures, objects, all]
resize: [256, 256] 
data_path: /data/data_wbw/data/cropped_tyre/1-按规格显著病茨/7.00R16-8PR[CR908+A]朝阳无内 AA/train_2000/1
save_path: [output/, *model, _, *backbone, _, *category]
save_name: &save_name 7.00R16-8PR_2000_1.pth

# train arguments
epochs: 100
do_eval: False  # After training, whether to eval model;

lr: 0.4
momentum: 0.9
weight_decay: 1.0e-4

# val and predict arguments
model_path: [output/, *model, _, *backbone, _, *category, /, *save_name]

# val arguments
compute_pro: False

# predict arguments
save_pic: True
img_path: /data/data_wbw/data/cropped_tyre/1-按规格显著病茨/7.00R16-8PR[CR908+A]朝阳无内 AA/68_2000/1 # 48.jpg # /data/data_wbw/data/cropped_tyre/006163125019100_3/test/A011160517_0.jpg
result_path: [output/, *model, _, *backbone, _, *category, '/7.00R16-8PR[CR908+A]朝阳无内 AA_68_2000_1']
threshold: 0.005