# common arguments
device: cuda:0
seed: 3
model: &model local_coreset
backbone: &backbone resnet18  # Support resnet18, resnet50, wide_resnet50_2
method: local_coreset # projection method, one of [sample, ortho, svd_ortho, gaussian, coreset]
k: 10  # using feature channels
pretrained_model_path: null # checkpoints/resnet18.pth

# dataset arguments
batch_size: 1
num_workers: 0
category: &category wood
resize: [256, 256]
crop_size: [256, 256]
data_path: /data/data_wbw/data/mvtec_anomaly_detection/wood/train/good/
save_path: [output/, *model, _, *backbone, _, *category]
save_name: &save_name wood.pth

# train arguments
do_eval: False  # After training, whether to eval model;

# val and predict arguments
save_pic: True # Whether to save one output example picture in val and predict;
model_path: [output/, *model, _, *backbone, _, *category, /, *save_name]

# predict arguments
img_path: /data/data_wbw/data/mvtec_anomaly_detection/wood/test/hole
result_path: [output/, *model, _, *backbone, _, *category, '/hole']
threshold: 2.2